import { SeedCategoryDefinition } from './catalog-seed-data';

export const categoriesSeedData: SeedCategoryDefinition[] = [
  {
    "name": "Men's Fashion",
    "description": "<p>Discover the latest in Men’s Fashion — from casual weekend tees to sharp tailored suits, denim, ethnic wear, and active loungewear.</p>",
    "image": "/storage/categories/mens_fashion_main.png",
    "secondaryImage": "/storage/categories/mens_fashion_banner.png",
    "link": "/category/mens-fashion",
    "domainAttributes": [
      "Color",
      "Clothing Size"
    ],
    "subcategories": [
      "Casual T-Shirts",
      "Polo T-Shirts",
      "Oversized Graphic Tees",
      "Henley Neck T-Shirts",
      "Casual Button-Down Shirts",
      "Formal Office Shirts",
      "Denim Shirts",
      "Linen Summer Shirts",
      "Hawaiian Printed Shirts",
      "Flannel Plaid Shirts",
      "Slim Fit Denim Jeans",
      "Relaxed Straight Jeans",
      "Cargo Joggers & Pants",
      "Chino Trousers",
      "Formal Dress Trousers",
      "Track Pants & Sweatpants",
      "Bermuda & Chino Shorts",
      "Gym & Athletic Shorts",
      "Sweatshirts & Crewnecks",
      "Pullover & Zip Hoodies",
      "Knit Sweaters & Pullovers"
    ]
  },
  {
    "name": "Women's Fashion",
    "description": "<p>Explore trendsetting Women’s Fashion featuring elegant sarees, designer lehengas, contemporary dresses, denim, formal workwear, and loungewear.</p>",
    "image": "/storage/categories/womens_fashion_main.png",
    "secondaryImage": "/storage/categories/womens_fashion_banner.png",
    "link": "/category/womens-fashion",
    "domainAttributes": [
      "Color",
      "Clothing Size"
    ],
    "subcategories": [
      "Traditional Silk Sarees",
      "Georgette & Chiffon Sarees",
      "Cotton Daily Sarees",
      "Designer Partywear Sarees",
      "Daily Wear Kurtis & Tunics",
      "Anarkali Kurta Sets",
      "Salwar Suit Sets",
      "Bridal & Festive Lehengas",
      "Ethnic Gowns",
      "Palazzo & Sharara Sets",
      "Dupattas, Shawls & Stoles",
      "Stitched Saree Blouses",
      "Crop Tops & Tank Tops",
      "Casual T-Shirts & Graphic Tees",
      "Formal Work Shirts",
      "Peplum & Wrap Tops",
      "Maxi & Floor Length Dresses",
      "A-Line & Shift Dresses",
      "Bodycon Party Dresses",
      "Jumpsuits & Playsuits",
      "High Waist Skinny Jeans",
      "Wide Leg & Mom Jeans"
    ]
  },
  {
    "name": "Kids & Baby Fashion",
    "description": "<p>Adorable, super-comfortable, and durable fashion for newborns, toddlers, boys, and girls for everyday play, school, and festive celebrations.</p>",
    "image": "/storage/categories/kids_fashion_main.png",
    "secondaryImage": "/storage/categories/kids_fashion_banner.png",
    "link": "/category/kids-baby-fashion",
    "domainAttributes": [
      "Color",
      "Kids Age & Size"
    ],
    "subcategories": [
      "Boys Graphic T-Shirts",
      "Boys Polo & Casual Shirts",
      "Boys Denim Jeans & Dungarees",
      "Boys Cotton Shorts",
      "Boys Track Pants & Joggers",
      "Boys Ethnic Kurta Sets",
      "Boys Party Suits & Waistcoats",
      "Boys Sweaters & Cardigans",
      "Boys Hoodies & Jackets",
      "Boys Sleepwear & Night Suits",
      "Boys Innerwear & Vests",
      "Girls Frocks & Party Dresses",
      "Girls Casual Tops & Tees",
      "Girls Jeans & Jeggings",
      "Girls Skirts & Shorts",
      "Girls Leggings & Tights",
      "Girls Festive Lehengas",
      "Girls Ethnic Kurtis & Suits",
      "Girls Sweaters & Cardigans",
      "Girls Winter Jackets & Coats",
      "Girls Nightwear Pajamas"
    ]
  },
  {
    "name": "Footwear & Shoes",
    "description": "<p>Step out in style and comfort with sneakers, formal brogues, running shoes, heels, flats, sandals, boots, and orthopedic footwear.</p>",
    "image": "/storage/categories/footwear_main.png",
    "secondaryImage": "/storage/categories/footwear_banner.png",
    "link": "/category/footwear-shoes",
    "domainAttributes": [
      "Color",
      "Footwear Size"
    ],
    "subcategories": [
      "Men Road Running Shoes",
      "Men Lifestyle Sneakers",
      "Men Formal Oxford Shoes",
      "Men Derby Dress Shoes",
      "Men Leather Brogues",
      "Men Monk Strap Shoes",
      "Men Casual Slip-on Loafers",
      "Men Driving Moccasins",
      "Men Sandals & Floaters",
      "Men Flip Flops & House Slippers",
      "Men Chelsea & Ankle Boots",
      "Men Football & Turf Cleats",
      "Men Gym & Cross Training Shoes",
      "Men Hiking & Trekking Boots",
      "Women High Stiletto Heels",
      "Women Block Heels",
      "Women Wedge Sandals",
      "Women Ballet Flats & Ballerinas",
      "Women Casual White Sneakers",
      "Women Running & Walking Shoes",
      "Women Ankle & Knee High Boots",
      "Women Mules & Clogs"
    ]
  },
  {
    "name": "Smartphones & Accessories",
    "description": "<p>Latest 5G smartphones, flagship devices, rugged cases, tempered protectors, fast chargers, power banks, and essential mobile accessories.</p>",
    "image": "/storage/categories/smartphones_main.png",
    "secondaryImage": "/storage/categories/smartphones_banner.png",
    "link": "/category/smartphones-accessories",
    "domainAttributes": [
      "Color",
      "Storage Capacity"
    ],
    "subcategories": [
      "Flagship 5G Smartphones",
      "Budget Android Smartphones",
      "Apple iPhones & iOS Devices",
      "Gaming Specific Smartphones",
      "Foldable & Flip Smartphones",
      "Feature Keypad Phones",
      "Certified Refurbished Phones",
      "Shockproof Back Covers",
      "Genuine Leather Flip Cases",
      "Clear Transparent Bumper Cases",
      "Tempered Glass Screen Guards",
      "Matte Privacy Screen Protectors",
      "UV Curved Screen Protectors",
      "Camera Lens Protector Rings",
      "GaN 65W+ Fast Wall Chargers",
      "Dual Port USB-C Adapters",
      "Braided USB-C to Type-C Cables",
      "Fast Charging Lightning Cables",
      "Magnetic 3-in-1 Charging Cables",
      "10000mAh Slim Power Banks",
      "20000mAh High Capacity Power Banks",
      "Qi Wireless Charging Pads"
    ]
  },
  {
    "name": "Laptops, Computers & Parts",
    "description": "<p>High-speed gaming laptops, ultrabooks, desktop towers, mechanical keyboards, monitors, NVMe SSDs, graphics cards, and PC peripherals.</p>",
    "image": "/storage/categories/computers_main.png",
    "secondaryImage": "/storage/categories/computers_banner.png",
    "link": "/category/laptops-computers",
    "domainAttributes": [
      "Color",
      "RAM Memory"
    ],
    "subcategories": [
      "High Performance Gaming Laptops",
      "Thin & Light Ultrabooks",
      "Commercial Business Laptops",
      "2-in-1 Convertible Touch Laptops",
      "Apple MacBooks (Air & Pro)",
      "Budget Student Chromebooks",
      "All-in-One Desktop PCs",
      "Mini Desktop PCs",
      "Pre-built Gaming PC Towers",
      "24-27 Inch IPS Computer Monitors",
      "34 Inch Curved UltraWide Monitors",
      "144Hz+ High Refresh Gaming Monitors",
      "RGB Mechanical Keyboards",
      "Wireless Ergonomic Keyboards",
      "Slim Membrane Keyboards",
      "Wireless Ergonomic Mice",
      "High Precision Gaming Mice",
      "Large Extended Desk Mousepads",
      "1080p / 4K USB Webcams",
      "USB Conference Microphones",
      "Stereo Desktop PC Speakers",
      "Padded Laptop Backpacks"
    ]
  },
  {
    "name": "Audio & Headphones",
    "description": "<p>Immerse yourself in crystal clear sound with Active Noise Cancelling headphones, TWS earbuds, Bluetooth speakers, soundbars, and studio audio.</p>",
    "image": "/storage/categories/audio_main.png",
    "secondaryImage": "/storage/categories/audio_banner.png",
    "link": "/category/audio-headphones",
    "domainAttributes": [
      "Color",
      "Warranty Duration"
    ],
    "subcategories": [
      "True Wireless Earbuds (TWS)",
      "Active Noise Cancelling Earbuds",
      "Sports Wireless Neckbands",
      "Wired 3.5mm In-Ear Earphones",
      "Over-Ear ANC Wireless Headphones",
      "On-Ear Lightweight Headphones",
      "Studio Reference Monitor Headphones",
      "Gaming Headsets with Surround Sound",
      "Compact Bluetooth Portable Speakers",
      "Rugged Waterproof Outdoor Speakers",
      "RGB Party Bluetooth Speakers",
      "Dolby Atmos TV Soundbars",
      "5.1 Surround Home Theater Systems",
      "Smart Assistant Voice Speakers",
      "Trolley PA Karaoke Party Speakers",
      "Hi-Fi Bookshelf Speakers",
      "In-Ceiling Architectural Speakers",
      "Audio Amplifiers & AV Receivers",
      "Hi-Res Portable DAC Amps",
      "USB Studio Podcast Microphones",
      "Wireless Lavalier Lapel Microphones"
    ]
  },
  {
    "name": "Televisions & Home Theater",
    "description": "<p>Upgrade your living room entertainment with 4K UHD Smart TVs, OLED displays, cinema projectors, streaming devices, and wall mount systems.</p>",
    "image": "/storage/categories/tvs_main.png",
    "secondaryImage": "/storage/categories/tvs_banner.png",
    "link": "/category/televisions-home-theater",
    "domainAttributes": [
      "Screen Size",
      "Warranty Duration"
    ],
    "subcategories": [
      "4K Ultra HD Smart LED TVs",
      "OLED Self-Lit Smart TVs",
      "QLED Quantum Dot TVs",
      "8K Ultra HD Smart TVs",
      "Mini-LED Flagship Smart TVs",
      "Budget 32 Inch HD Ready TVs",
      "43 Inch Full HD / 4K Smart TVs",
      "50-55 Inch 4K UHD Smart TVs",
      "65 Inch+ Theater Sized TVs",
      "Home Cinema Full HD Projectors",
      "Portable Mini Smart Projectors",
      "Ultra Short Throw 4K Laser Projectors",
      "Motorized Projector Pull-Down Screens",
      "4K Streaming Media HDMI Sticks",
      "Android TV & Google TV Boxes",
      "Apple TV 4K Media Players",
      "Digital Set Top Boxes & Receivers",
      "Fixed TV Wall Mount Brackets",
      "Full Motion Swivel TV Wall Mounts",
      "Motorized Ceiling TV Mounts",
      "Modern Floor Easel TV Stands"
    ]
  },
  {
    "name": "Cameras, Drones & Optics",
    "description": "<p>Capture every moment in cinema quality with professional DSLR, mirrorless cameras, 4K drones, prime lenses, gimbals, and studio lighting gear.</p>",
    "image": "/storage/categories/cameras_main.png",
    "secondaryImage": "/storage/categories/cameras_banner.png",
    "link": "/category/cameras-drones",
    "domainAttributes": [
      "Color",
      "Warranty Duration"
    ],
    "subcategories": [
      "Full Frame Mirrorless Cameras",
      "APS-C Sensor DSLR Cameras",
      "4K Waterproof Action Cameras",
      "360 Degree Panoramic Cameras",
      "Instant Film Print Cameras",
      "Compact Point & Shoot Cameras",
      "Professional Cinema Cameras",
      "4K GPS Camera Drones",
      "Mini Foldable Travel Drones",
      "FPV High Speed Racing Drones",
      "Fast Prime Photography Lenses",
      "Telephoto Zoom Lenses",
      "Ultra Wide Angle Landscape Lenses",
      "Macro Close-up Lenses",
      "UV & CPL Circular Polarizer Filters",
      "Variable Neutral Density (ND) Filters",
      "Heavy Duty Carbon Fiber Tripods",
      "Fluid Video Monopods with Feet",
      "3-Axis Handheld Camera Gimbals",
      "External Camera Speedlight Flashes",
      "Studio Softbox Continuous Lighting Kits"
    ]
  },
  {
    "name": "Smart Watches & Wearables",
    "description": "<p>Stay connected and monitor your fitness with AMOLED smartwatches, Bluetooth calling watches, GPS sports trackers, and smart rings.</p>",
    "image": "/storage/categories/wearables_main.png",
    "secondaryImage": "/storage/categories/wearables_banner.png",
    "link": "/category/smart-watches-wearables",
    "domainAttributes": [
      "Color",
      "Screen Size"
    ],
    "subcategories": [
      "Men Bluetooth Calling Smartwatches",
      "Women Fashion AMOLED Smartwatches",
      "Fitness Bands & Activity Trackers",
      "Rugged Outdoor Military Smartwatches",
      "GPS Multisport Running Watches",
      "Smart Health Rings (Titanium)",
      "Kids Safety GPS Tracker Watches",
      "Luxury Stainless Steel Smartwatches",
      "Virtual Reality (VR) All-in-One Headsets",
      "Smart Audio Sunglasses with Bluetooth",
      "Augmented Reality (AR) Smart Glasses",
      "Wearable ECG & Heart Rate Monitors",
      "Medical Grade Pulse Oximeter Clips",
      "Smart Body Composition Scales",
      "Smartwatch Breathable Silicone Straps",
      "Smartwatch Stainless Steel Metal Straps",
      "Smartwatch Genuine Leather Bands",
      "Smartwatch Sport Loop Nylon Bands",
      "Magnetic Milanese Loop Metal Straps",
      "Full Coverage 3D Screen Protectors",
      "Shockproof Smartwatch Bumper Cases"
    ]
  },
  {
    "name": "Home Appliances & Cooling",
    "description": "<p>Equip your home with energy-efficient split ACs, frost-free refrigerators, fully automatic washing machines, air purifiers, and water geysers.</p>",
    "image": "/storage/categories/appliances_main.png",
    "secondaryImage": "/storage/categories/appliances_banner.png",
    "link": "/category/home-appliances",
    "domainAttributes": [
      "Volume & Capacity",
      "Warranty Duration"
    ],
    "subcategories": [
      "5 Star Inverter Split Air Conditioners",
      "Window Air Conditioners",
      "Portable Floor Standing Air Conditioners",
      "Double Door Frost-Free Refrigerators",
      "Single Door Direct Cool Refrigerators",
      "Side-by-Side Large Refrigerators",
      "French Door Multizone Refrigerators",
      "Deep Chest Freezers",
      "Front Load Fully Automatic Washing Machines",
      "Top Load Fully Automatic Washing Machines",
      "Semi-Automatic Washing Machines",
      "Washer Dryer Combo Machines",
      "Built-in & Freestanding Dishwashers",
      "Convection Microwave Ovens with Grill",
      "Solo Digital Microwave Ovens",
      "Oven Toaster Grillers (OTG)",
      "HEPA Filter Room Air Purifiers",
      "Ultrasonic Cool Mist Humidifiers",
      "Commercial & Home Dehumidifiers",
      "BLDC Energy Efficient Ceiling Fans",
      "High Speed Pedestal Standing Fans"
    ]
  },
  {
    "name": "Kitchen, Dining & Cookware",
    "description": "<p>Master your culinary skills with heavy mixer grinders, air fryers, non-stick cookware, tri-ply stainless steel sets, and ceramic dinnerware.</p>",
    "image": "/storage/categories/kitchen_main.png",
    "secondaryImage": "/storage/categories/kitchen_banner.png",
    "link": "/category/kitchen-dining",
    "domainAttributes": [
      "Material",
      "Volume & Capacity"
    ],
    "subcategories": [
      "750W / 1000W Heavy Mixer Grinders",
      "Multifunctional Food Processors",
      "Stainless Steel Hand Blenders",
      "Electric Rapid Boil Kettles",
      "Touch Control Induction Cooktops",
      "2-Burner Toughened Glass Gas Stoves",
      "3-Burner Automatic Ignition Gas Stoves",
      "4-Burner Built-in Gas Hobs",
      "Digital Touch Screen Air Fryers",
      "Electric Automatic Rice Cookers",
      "Grill Sandwich & Panini Makers",
      "2-Slice & 4-Slice Pop-up Bread Toasters",
      "Belgian Waffle Maker Machines",
      "Espresso & Cappuccino Coffee Machines",
      "Cold Press Masticating Slow Juicers",
      "Electric Food & Vegetable Choppers",
      "Automatic Egg Boilers",
      "Non-Stick Induction Frying Pans",
      "Hard Anodized Pressure Cookers",
      "Tri-Ply Stainless Steel Pressure Cookers",
      "Tri-Ply Stainless Steel Kadhai & Woks",
      "Pre-Seasoned Cast Iron Skillets"
    ]
  },
  {
    "name": "Furniture & Living Room",
    "description": "<p>Elevate your interior living space with plush fabric sofas, Sheesham wood coffee tables, ergonomic recliners, bookshelves, and shoe units.</p>",
    "image": "/storage/categories/furniture_main.png",
    "secondaryImage": "/storage/categories/furniture_banner.png",
    "link": "/category/furniture-living-room",
    "domainAttributes": [
      "Color",
      "Material"
    ],
    "subcategories": [
      "3-Seater Fabric Sofas",
      "L-Shaped Sectional Corner Sofas",
      "Single Seater Leatherette Recliner Chairs",
      "Dual Motor Electric Recliners",
      "Convertible Wooden Sofa Cum Beds",
      "Chesterfield Tufted Luxury Sofas",
      "Solid Sheesham Wood Sofa Sets",
      "Velvet Fabric Accent Armchairs",
      "Wingback Reading Lounge Chairs",
      "Solid Wood Center Coffee Tables",
      "Nesting Coffee Tables (Set of 3)",
      "Tempered Glass Side & End Tables",
      "Foyer Entryway Console Tables",
      "Wall Mounted TV Entertainment Units",
      "Floor Standing Wooden TV Cabinets",
      "Open Display Bookcases & Shelves",
      "Floating Wall Mounted Shelving Units",
      "Glass Door Trophy Display Cabinets",
      "Wooden Shoe Racks with Cushion Bench",
      "Multi-Tier Closed Door Shoe Cabinets",
      "Entryway Storage Benches"
    ]
  },
  {
    "name": "Bedroom, Mattresses & Bedding",
    "description": "<p>Create your dream sleep sanctuary with king size storage beds, orthopedic memory foam mattresses, Egyptian cotton bedsheets, and comforters.</p>",
    "image": "/storage/categories/bedroom_main.png",
    "secondaryImage": "/storage/categories/bedroom_banner.png",
    "link": "/category/bedroom-mattresses",
    "domainAttributes": [
      "Color",
      "Material"
    ],
    "subcategories": [
      "King Size Solid Wood Beds with Storage",
      "Queen Size Hydraulic Storage Beds",
      "Single Beds with Underbed Drawers",
      "Upholstered Headboard Platform Beds",
      "Solid Sheesham Wood Teak Finished Beds",
      "Kids Bunk Beds with Safety Rails",
      "Pull-Out Trundle Daybeds",
      "Orthopedic High Density Memory Foam Mattresses",
      "Pocket Spring Zero Disturbance Mattresses",
      "Natural Latex Foam Eco Mattresses",
      "Dual Comfort Reversible Mattresses",
      "Foldable Tri-Fold Floor Mattresses",
      "Waterproof Breathable Mattress Protectors",
      "2-Inch Plush Memory Foam Mattress Toppers",
      "2-Door Engineered Wood Wardrobes",
      "3-Door Wardrobes with Mirror & Drawers",
      "4-Door Spacious Master Wardrobes",
      "Sliding Door Modern Wardrobes",
      "Dressing Tables with LED Mirror",
      "Chest of 4/5 Storage Drawers",
      "Bedside Nightstand Tables with Drawers"
    ]
  },
  {
    "name": "Home Decor & Lighting",
    "description": "<p>Personalize your spaces with canvas art, metal wall hangings, decorative clocks, LED chandeliers, aromatic candles, and plush rugs.</p>",
    "image": "/storage/categories/homedecor_main.png",
    "secondaryImage": "/storage/categories/homedecor_banner.png",
    "link": "/category/home-decor-lighting",
    "domainAttributes": [
      "Color",
      "Material"
    ],
    "subcategories": [
      "Framed Canvas Wall Paintings",
      "Modern Abstract Metal Wall Sculptures",
      "Silent Sweep Decorative Wall Clocks",
      "Antique Wooden Pendulum Wall Clocks",
      "Bedside Ceramic & Wood Table Lamps",
      "Tripod Floor Standing Corner Lamps",
      "Modern LED Crystal Chandeliers",
      "Nordic Pendant Ceiling Hanging Lights",
      "Recessed Ceiling LED Spotlights",
      "Decorative Fairy String Lights for Diwali",
      "Solar Waterproof Outdoor Garden Lights",
      "Smart Wi-Fi RGB Color Changing Bulbs",
      "Soy Wax Scented Aromatherapy Candles",
      "Ultrasonic Essential Oil Aroma Diffusers",
      "Handcrafted Ceramic Flower Vases",
      "Nordic Minimalist Glass Vases",
      "Artificial Potted Plants (Areca/Fiddle)",
      "Bonsai & Succulent Tabletop Decor",
      "Decorative Sunburst Metal Wall Mirrors",
      "Full Length Arch Standing Mirrors",
      "Plush Fluffy Living Room Area Carpets",
      "Handwoven Cotton Dhurrie Rugs"
    ]
  },
  {
    "name": "Beauty, Cosmetics & Makeup",
    "description": "<p>Express your beauty with long-lasting matte lipsticks, lightweight foundations, eyeshadow palettes, kajal, waterproof mascaras, and makeup brushes.</p>",
    "image": "/storage/categories/beauty_main.png",
    "secondaryImage": "/storage/categories/beauty_banner.png",
    "link": "/category/beauty-cosmetics",
    "domainAttributes": [
      "Color",
      "Volume & Capacity"
    ],
    "subcategories": [
      "Velvet Matte Transfer-Proof Lipsticks",
      "Hydrating Liquid Lipsticks",
      "Glossy Non-Sticky Lip Tints & Oils",
      "Tinted Nourishing Lip Balms",
      "Full Coverage Liquid Foundations",
      "SPF 30 All-in-One BB & CC Creams",
      "Creamy Concealers & Color Correctors",
      "Oil Control Matte Compact Powders",
      "Long-Lasting Makeup Setting Sprays",
      "Pore Minimizing Face Primers",
      "Contour, Bronzer & Highlighter Palettes",
      "Silk Pigment Powder Blushes",
      "18-Color Nude Eyeshadow Palettes",
      "Waterproof Precision Liquid Eyeliners",
      "Smudge-Proof 24H Kajal & Kohl Pencils",
      "Volumizing & Lengthening Waterproof Mascaras",
      "Precision Eyebrow Pencils & Pomades",
      "Reusable 3D Silk False Eyelashes",
      "Professional 15-Piece Makeup Brush Sets",
      "Teardrop Beauty Blender Makeup Sponges",
      "Hydrating Micellar Cleansing Water",
      "Melt-Away Makeup Cleansing Balms"
    ]
  },
  {
    "name": "Personal Care & Grooming",
    "description": "<p>Complete grooming essentials for men and women including cordless beard trimmers, electric shavers, oral care, fragrances, and bath sets.</p>",
    "image": "/storage/categories/grooming_main.png",
    "secondaryImage": "/storage/categories/grooming_banner.png",
    "link": "/category/personal-care-grooming",
    "domainAttributes": [
      "Color",
      "Volume & Capacity"
    ],
    "subcategories": [
      "Cordless Fast Charge Beard Trimmers",
      "Foil & Rotary Wet/Dry Electric Shavers",
      "Nose, Ear & Eyebrow Precision Trimmers",
      "All-in-One Multi-Grooming Body Kits",
      "Traditional Double Edge Safety Razors",
      "5-Blade Shaving Razor Cartridges",
      "Hydrating Shaving Creams & Foams",
      "Alcohol-Free Aftershave Balms & Lotions",
      "Badger Bristle Wooden Shaving Brushes",
      "Organic Beard Growth Oils & Serums",
      "Beard Softener Washes & Conditioners",
      "Natural Hold Beard Wax & Styling Butters",
      "Professional Hair Clippers with Guide Combs",
      "Ionic Hair Dryers for Men & Women",
      "Long-Lasting Gas-Free Body Deodorant Sprays",
      "Luxury Eau De Parfum (EDP) for Men",
      "Designer Eau De Toilette (EDT) for Women",
      "Floral & Fruity Body Mists for Women",
      "Pocket Perfume Sprays (20ml)",
      "Roll-on Antiperspirant Deodorants",
      "Sonic Electric Toothbrushes with 4 Modes"
    ]
  },
  {
    "name": "Skincare, Haircare & Bath",
    "description": "<p>Nourish your skin and hair with dermatologist-approved face serums, SPF sunscreens, anti-dandruff shampoos, hair masks, and body butters.</p>",
    "image": "/storage/categories/skincare_main.png",
    "secondaryImage": "/storage/categories/skincare_banner.png",
    "link": "/category/skincare-haircare",
    "domainAttributes": [
      "Volume & Capacity",
      "Warranty Duration"
    ],
    "subcategories": [
      "Gentle Foaming Daily Face Cleansers",
      "Salicylic Acid Anti-Acne Face Washes",
      "Exfoliating Walnut & Apricot Face Scrubs",
      "Hydrating Rosewater & Niacinamide Toners",
      "20% Vitamin C Face Glow Serums",
      "Pure Hyaluronic Acid 2% Hydrating Serums",
      "10% Niacinamide + Zinc Blemish Serums",
      "Retinol 0.5% Night Anti-Aging Serums",
      "2% Salicylic Acid Blackhead Clearing Serums",
      "Ultra Light Gel Moisturizers with Ceramide",
      "SPF 50 PA++++ Matte Sunscreen Gels",
      "Invisible Sunscreen Sticks with Centella",
      "Mineral Zinc Oxide Sunscreens for Sensitive Skin",
      "Caffeine Under-Eye Dark Circle Creams",
      "Deep Purifying Kaolin Clay Face Masks",
      "Charcoal Peel-off Blackhead Face Masks",
      "Overnight Rejuvenating Sleeping Masks",
      "Nourishing Berry Lip Sleeping Masks",
      "Anti-Dandruff Ketoconazole Shampoos",
      "Sulphate-Free & Paraben-Free Shampoos",
      "Onion & Biotin Hair Fall Control Shampoos",
      "Keratin Smooth Deep Conditioners"
    ]
  }
];
